In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/home/scitator/.conda/envs/python2/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


In [2]:
data = pd.read_csv('./chekins.csv')

In [3]:
data.head()

id  user_id  venue_id   latitude   longitude
0  984222    15824      5222  38.895112  -77.036366
1  984234    44652      5222  33.800745  -84.410520
2  984291   105054      5222  45.523452 -122.676207
3  984318  2146539      5222  40.764462 -111.904565
4  984232    93870    380645  33.448377 -112.074037

In [4]:
data[['latitude', 'longitude']].head()

latitude   longitude
0  38.895112  -77.036366
1  33.800745  -84.410520
2  45.523452 -122.676207
3  40.764462 -111.904565
4  33.448377 -112.074037

In [5]:
from sklearn.cluster import MeanShift

In [6]:
cluster_clf = MeanShift(bandwidth=0.1, min_bin_freq=15, n_jobs=3)

In [7]:
X = data[['latitude', 'longitude']].values[:,:]

In [8]:
X

array([[  38.8951118,  -77.0363658],
       [  33.800745 ,  -84.41052  ],
       [  45.5234515, -122.6762071],
       ..., 
       [  42.7653662,  -71.467566 ],
       [  42.439479 ,  -83.7438303],
       [  42.331427 ,  -83.0457538]])

In [9]:
cluster_clf.fit(X)

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=15,
     n_jobs=3, seeds=None)

In [15]:
centers = cluster_clf.cluster_centers_

In [13]:
office_places = {
    "Los Angeles":(33.751277, -118.188740),
    "Miami":(25.867736, -80.324116),
    "London":(51.503016, -0.075479),
    "Amsterdam":(52.378894, 4.885084),
    "Beijing":(39.366487, 117.036146),
    "Sydney":(-33.868457, 151.205134)
    }

In [22]:
def dist_2d(first, second):
    return np.sqrt((first[0] - second[0]) ** 2 + (first[1] - second[1]) ** 2)

def dist_to_offices(x):
    distances = [(x, dist_2d(x, y)) for key, y in office_places.iteritems()]
    return min(distances, key = lambda t: t[1])

In [23]:
closest_offices = map(dist_to_offices, centers)

In [26]:
sorted(closest_offices, key= lambda x: x[1])[:20]

[(array([ -33.86614607,  151.20708242]), 0.003022703449948845),
 (array([ 52.37248935,   4.89226825]), 0.0096246032756686951),
 (array([ 25.84620622, -80.31124452]), 0.025083985626543605),
 (array([ 51.50305542,  -0.1271134 ]), 0.05163441574703833),
 (array([  33.81127536, -118.14433437]), 0.074643578609750835),
 (array([ 25.7870861 , -80.21512757]), 0.13558349109045645),
 (array([ 52.50144115,   4.95388735]), 0.14054075901440111),
 (array([ -33.75067218,  151.08258934]), 0.16997193155620183),
 (array([ 52.3080507,   5.0406217]), 0.17091152470263668),
 (array([ -33.9230724 ,  151.03596687]), 0.17776490350284782),
 (array([ 26.00505198, -80.20559812]), 0.18138954325825918),
 (array([  33.89848762, -118.06225896]), 0.19408354098497979),
 (array([ 52.28383697,   4.71420272]), 0.1955409116974676),
 (array([ 51.48036586,  -0.30832346]), 0.23394352367571658),
 (array([ -33.6550392,  151.3203137]), 0.24251499056538242),
 (array([ 52.37985987,   4.64044448]), 0.24464142667227903),
 (array([ 51